version: '3.5'

services:
  api01: &api
    build: .
    hostname: api01
    environment:
      - MONGO_URI=mongodb://db:27017/rinha
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app
    tty: true
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "200MB"
  
  api02:
    <<: *api
    hostname: api02
    ports:
      - "3001:3001"
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "10MB"

  db:
    image: mongo:7.0.5-jammy
    hostname: db
    environment:
      - MONGO_INITDB_DATABASE=rinha
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "140MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
    